name: Release
on:
  workflow_dispatch:
  push:
    branches:
      - master
      - main

jobs:
  release:
    name: releaser
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: 'moul/quicssh'
          
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
       
   
      - name: Creat file
        uses: 1arp/create-a-file-action@0.2
        with:
          file: .goreleaser.yml
          content: |
            release:
              github:
                owner: diseq
                name: quicssh
                
            before:
              hooks:
                - go mod download
                - go mod tidy
                
            builds:
              -
                goos: [linux, windows]
                goarch: [amd64, arm, arm64]
            archives:
              - wrap_in_directory: true
            checksum:
              name_template: 'checksums.txt'
            snapshot:
              name_template: "{{ .Tag }}"
            changelog:
              sort: asc
              filters:
                exclude:
                - '^docs:'
                - '^test:'
       
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser
          version: latest
          args: release --snapshot --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      -
        name: Upload assets
        uses: actions/upload-artifact@v2
        with:
          name: quicssh
          path: dist/*          
